server:
  hostname: "localhost"
  port: 8000

image_registry:
  enabled: true
  hostname: "localhost"
  port: 5000
  create_namespace_on_push: true
  create_repository_on_push: true

upstream_registry:
  enabled: true

admin:
  username: "admin"
  password: "admin"
  email: admin@test.com
  create_account: true

database:
  type: "sqlite"
  path: "${app_home}/server/registry_sqlite.db"
  scripts_path: "${app_home}/server/db-scripts/sqlite/registry.sql"

storage:
  type: "lfs"
  path: "${app_home}/server/temp"

notification:
  # By default, email notification is disabled. To invite new user, email configuration must be enabled.
  email:
    enabled: false
    smtp_host: ""
    smtp_port: 0
    smtp_user: ""
    smtp_password: ""
    from_address: ""

webapp:
  enable_ui: false
  dist_path: ${app_home}/webapp/build

development:
  enable: true
  mock_email: true # Instead of sending email, print the link/uuid in logs

security:
# Management APIs are protected by auth_token
  auth_token:
    issuer: "open-image-registry"
    algorithm: "ES256"
    private_key_path: "${app_home}/server/certs/jwt_es256_private.pem"
    public_key_path: "${app_home}/server/certs/jwt_es256_public.pem"
    expiry_seconds: 900